# Generated by Django 3.2.9 on 2022-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0005_auto_20220311_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acat_settings',
            name='Setting',
            field=models.CharField(max_length=100),
        ),
    ]
