# Generated by Django 4.0.3 on 2022-03-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0011_alter_subattrib_common_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonNameList',
        ),
    ]
