# Generated by Django 3.2.9 on 2022-03-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='X509v3_Extension_Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates', models.CharField(max_length=24)),
            ],
        ),
    ]
