# Generated by Django 3.2.9 on 2022-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0002_auto_20220311_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setting', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Setting'],
            },
        ),
        migrations.RemoveField(
            model_name='sub_settings',
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
        migrations.DeleteModel(
            name='Sub_Settings',
        ),
    ]
