# Generated by Django 3.2.9 on 2022-03-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0003_auto_20220311_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Setting',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
