# Generated by Django 3.2.9 on 2022-03-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0004_alter_settings_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='acat_settings',
        ),
        migrations.AlterModelOptions(
            name='acat_settings',
            options={},
        ),
    ]
