# Generated by Django 3.2.9 on 2022-03-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0006_alter_acat_settings_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acat_settings',
        ),
    ]
