# Generated by Django 4.0.3 on 2022-03-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0010_alter_commonnamelist_commonname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subattrib',
            name='common_name',
            field=models.CharField(max_length=100),
        ),
    ]
