# Generated by Django 4.0.3 on 2022-03-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0012_delete_commonnamelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subattrib',
            name='created_at',
        ),
    ]
