# Generated by Django 4.0.3 on 2022-03-17 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0013_remove_subattrib_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subattrib',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
