# Generated by Django 4.0.3 on 2022-03-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acat_app', '0014_subattrib_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAttrib',
        ),
    ]
